# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: codespace <codespace@student.42.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/04/22 10:59:25 by codespace         #+#    #+#              #
#    Updated: 2026/04/22 13:52:18 by codespace        ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

Name		=	bureaucrat

DIR_OBJS	=	objs

SRCS_FILES	=	Bureaucrat.cpp	\
				main.cpp

OBJS_FILES	=	$(addprefix $(DIR_OBJS)/, $(SRCS_FILES:.c=.o))

